---
- hosts: all
  user: azureuser
  become: yes
  become_method: sudo
  become_user: root
  tasks:

          - name: Run script for audit
            command: sh disk.sh
            register: results

          - name: show results
            debug: msg={{ results.stdout.split('\n') }}
